# .github/workflows/metrics.yml
name: GitHub Metrics

on:
  schedule: [{cron: "0 0 * * *"}] # daily updates
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: winter000boy
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

          # Plugins
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 2%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: yes
          plugin_habits_trim: true

          # Repositories plugin (DYNAMIC repos list)
          plugin_repositories: yes
          plugin_repositories_affiliations: owner
          plugin_repositories_batch: 5
