# .github/workflows/snake.yml
name: Generate Snake Animation

on:
  schedule: # run automatically every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # allow manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Game from Contributions
        uses: Platane/snk@v3
        with:
          github_user_name: winter000boy
          outputs: dist/snake.svg

      - name: Push generated snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
